CREATE TABLE SPRINGMEMBER(
	ID VARCHAR2(30),
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGMEMBER_PK" PRIMARY KEY(ID),
	CONSTRAINT "SPRINGMEMBER_CK" CHECK("AUTH" IN ('A','U'))
);

CREATE TABLE SPRINGBOARD(
	SEQ NUMBER,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFER NUMBER NOT NULL,
	READCOUNT NUMBER,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "SPRINGBOARD_PK" PRIMARY KEY(SEQ),
	CONSTRAINT "SPRINGBOARD_FK" FOREIGN KEY("ID") REFERENCES SPRINGMEMBER("ID")
);

SELECT *
	FROM (
		SELECT SEQ, ID,
				CASE WHEN STEP > 0 
					THEN LPAD(' ',1+(STEP*6)*5, '&nbsp;') || '<img>' || CONCAT(SUBSTR(TITLE,0,10),'...')
					ELSE TITLE 
					END AS TITLE,
				CONTENT, STEP, DEPTH, REF, DELFLAG , REGDATE,
				ROW_NUMBER() OVER(ORDER BY REF DESC, STEP ASC) rn	
			FROM ANSWERBOARD a
		)
	WHERE rn BETWEEN 1 AND 5
	AND DELFLAG = 'N';

-- LPAD ('값', '총 문자길이', '채움문자')

SELECT CASE WHEN STEP > 0 THEN LPAD(' ',1+(STEP*6)*5, '&nbsp;') || CONCAT(SUBSTR(TITLE,0,10),'...') ELSE TITLE END AS TITLE
	FROM ANSWERBOARD a ;

INSERT INTO ANSWERBOARD
(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
VALUES((SELECT MAX(SEQ)+1 FROM ANSWERBOARD a), 'USER01', 
		(SELECT MAX(SEQ)+1 FROM ANSWERBOARD) || 'TEST ROOT 글입니다',
		(SELECT MAX(SEQ)+1 FROM ANSWERBOARD a1) || 'TEST ROOT 내용입니다',
		(SELECT MAX(SEQ)+1 FROM ANSWERBOARD a2), 0, 0, SYSDATE , 'N'
);

SELECT SEQ, ID, TITLE, CONTENT, TO_CHAR(REGDATE, 'YYYY-MM-DD hh24:mi:ss')
	FROM ANSWERBOARD a ;


-- 10g 부터 연속동작이 가능하다  update + delete
MERGE
	INTO ANSWERBOARD a
	USING DUAL
		ON (a."REF" = (SELECT REF FROM ANSWERBOARD a2 WHERE SEQ='2'))
	WHEN MATCHED THEN
		UPDATE 
			SET STEP = STEP +1 
			WHERE a.STEP > (SELECT STEP FROM ANSWERBOARD a3 WHERE SEQ = '2')
		DELETE WHERE (SEQ = '2');
			
			
UPDATE ANSWERBOARD 
	SET STEP = STEP +1
	WHERE 
		REF = (SELECT REF FROM ANSWERBOARD a WHERE SEQ = ''),
		STEP > (SELECT STEP FROM ANSWERBOARD a2 WHERE SEQ = '');

	
INSERT INTO ANSWERBOARD (SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
			VALUES((SELECT MAX(SEQ)+1 FROM ANSWERBOARD a), 'USER01', 
					(SELECT MAX(SEQ)+1 FROM ANSWERBOARD WHERE SEQ = '7') || 'TEST ROOT 글입니다',
					(SELECT MAX(SEQ)+1 FROM ANSWERBOARD a1 WHERE SEQ = '7') || 'TEST ROOT 내용입니다',
					(SELECT MAX(REF)+1 FROM ANSWERBOARD a2 WHERE SEQ = '7'), 0, 0, SYSDATE , 'N');
				
SELECT  *
 FROM ANSWERBOARD a ;
