CREATE TABLE EDUBOARD(
	SEQ NUMBER,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500),
	DELFLAG CHAR(1)NOT NULL,
	REGDATE DATE
);

ALTER TABLE EDUBOARD ADD CONSTRAINT EDUBOARD_PK PRIMARY KEY(SEQ);

CREATE SEQUENCE EDUBOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO WOON.EDUBOARD
	(SEQ, ID, TITLE, 
	CONTENT, DELFLAG, REGDATE)
VALUES(EDUBOARD_SEQ.NEXTVAL, '토마토', '멋쟁이 토마토', 
		'멋쟁이 토토마토', 'N', SYSDATE);
	
SELECT SEQ,ID,TITLE ,CONTENT ,DELFLAG ,REGDATE 
	FROM EDUBOARD e 
	ORDER BY REGDATE DESC;

UPDATE EDUBOARD 
	SET DELFLAG ='Y';
