CREATE TABLE NAVER_USERINFO(
	EMAIL VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	NICKNAME VARCHAR2(10) NOT NULL,
	MOBILE VARCHAR2(15),
	GENDER VARCHAR2(5),
	BIRTH VARCHAR2(12),
	REFRESHTOKEN VARCHAR2(1000) NOT NULL
);

CREATE TABLE KAKAO_USERINFO(
	EMAIL VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	NICKNAME VARCHAR2(10) NOT NULL,
	MOBILE VARCHAR2(15),
	GENDER VARCHAR2(5),
	BIRTH VARCHAR2(12),
	REFRESHTOKEN VARCHAR2(1000) NOT NULL
);

CREATE TABLE GOOGLE_USERINFO(
	EMAIL VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	NICKNAME VARCHAR2(10) NOT NULL
);

INSERT INTO WOON.KAKAO_USERINFO
(EMAIL, NAME, NICKNAME, MOBILE, GENDER, BIRTH, REFRESHTOKEN)
VALUES('', '', '', '', '', '', '');

INSERT INTO WOON.NAVER_USERINFO
(EMAIL, NAME, NICKNAME, MOBILE, GENDER, BIRTH, REFRESHTOKEN)
VALUES('', '', '', '', '', '', '');

INSERT INTO WOON.GOOGLE_USERINFO
(EMAIL, NAME, NICKNAME)
VALUES('', '', '');

SELECT COUNT(EMAIL)
	FROM(
	SELECT DISTINCT EMAIL
		FROM (
		    SELECT EMAIL FROM GOOGLE_USERINFO
		    UNION
		    SELECT EMAIL FROM NAVER_USERINFO
		    UNION
		    SELECT EMAIL FROM KAKAO_USERINFO
		))
		WHERE EMAIL ='1';
UPDATE KAKAO_USERINFO SET REFRESHTOKEN = '2'
	WHERE EMAIL ='1';