SELECT JOB_ID ,JOB_TITLE ,MIN_SALARY ,MAX_SALARY 
	FROM JOBS j ;

INSERT INTO HR.JOBS
(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES('', '', 0, 0);

ALTER TABLE JOBS ADD USEAGE VARCHAR2(2);

SELECT *
	FROM JOBS j ;

--㉠ JOBS table에 Add Column 해서 USEAGE 을 추가 하고 모든 컬럼의 값을 Y로 입력
UPDATE JOBS SET USEAGE ='Y';

UPDATE JOBS SET USEAGE ='N';

SELECT *
FROM USERINFO u ;

--회원가입
INSERT INTO USERINFO (ID,NAME,PASSWORD,EMAIL,AUTH,DELFLAG,JOINDATE)
VALUES('jeong','임정운','QWER1234','ASKDLKASLDS','U','N',SYSDATE);

--로그인
SELECT ID,NAME ,EMAIL ,AUTH ,DELFLAG ,JOINDATE 
	FROM USERINFO u 
	WHERE ID = 'user'
	AND PASSWORD = '1234';

--비밀번호
UPDATE USERINFO u2 SET PASSWORD ='1234'
	WHERE ID = 'user';

--페이징
	SELECT ID,NAME,EMAIL,AUTH,DELFLAG,JOINDATE
			FROM (SELECT ID,NAME,EMAIL,AUTH,DELFLAG,JOINDATE ,ROW_NUMBER() OVER(ORDER BY JOINDATE DESC) RN
				FROM USERINFO u )
			WHERE RN BETWEEN 1 AND 3;
--페이징 처리를 위한 UserCount
			



